package evgeniy.ryzhikov.guesstheflag.settings

const val NUMBER_OF_QUESTION_PER_ROUND = 5
const val ROUND_TIME_IN_MILLIS = 5000

const val STATISTIC_MULTIPLIER_FLAG_COUNTRY = 3
const val STATISTIC_MULTIPLIER_FLAG_REGION = 5
const val STATISTIC_MULTIPLIER_MAP_COUNTRY = 4
const val STATISTIC_MULTIPLIER_MAP_REGION = 6

const val POINTS_FOR_WRONG_FLAG_COUNTRY = -15
const val POINTS_FOR_WRONG_FLAG_REGION = -10
const val POINTS_FOR_WRONG_MAP_COUNTRY = -12
const val POINTS_FOR_WRONG_MAP_REGION = -8

class Settings {
}
